Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2020-12, with the labels that each got.

#338 Something cool I saw
  code/modules/mob/living/living.dm
Labels: Needs Vote

#333 [MIRROR] Removes monkey from rotation(again)
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update, Upstream PR Merged, Voted In

#342 [MIRROR] Adds an admin message for Delete Record (ALL) in case a AI or Cyborg does it
  code/game/machinery/computer/security.dm
Labels: Upstream PR Merged

#345 [MIRROR] Miscellaneous Mob Improvements
  beestation.dme
  code/__DEFINES/spaceman_dmm.dm
  code/datums/diseases/advance/symptoms/blobspores.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/obj_defense.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/kalo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Upstream PR Merged

#346 [MIRROR] Crate animation fixes and refractoring
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
  code/modules/mining/mine_items.dm
  icons/obj/crates.dmi
Labels: Upstream PR Merged

#361 Fixes the linting test
  .github/workflows/test.yml
Labels: GitHub

#360 [MIRROR] [s]Arbitrary file read vulnerability in antag tips.
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/tips.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Upstream PR Merged

#349 [MIRROR] [PORT] Smooth Doors from Yogstation
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/effects/overlays.dm
  code/modules/antagonists/clock_cult/clockwork_turfs.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/obj/doors/airlocks/abductor/abductor_airlock.dmi
  icons/obj/doors/airlocks/abductor/overlays.dmi
  icons/obj/doors/airlocks/centcom/centcom.dmi
  icons/obj/doors/airlocks/centcom/overlays.dmi
  icons/obj/doors/airlocks/clockwork/overlays.dmi
  icons/obj/doors/airlocks/clockwork/pinion_airlock.dmi
  icons/obj/doors/airlocks/cult/runed/cult.dmi
  icons/obj/doors/airlocks/cult/runed/overlays.dmi
  icons/obj/doors/airlocks/cult/unruned/cult.dmi
  icons/obj/doors/airlocks/cult/unruned/overlays.dmi
  icons/obj/doors/airlocks/external/arrivals_external.dmi
  icons/obj/doors/airlocks/external/external.dmi
  icons/obj/doors/airlocks/external/overlays.dmi
  icons/obj/doors/airlocks/glass_large/glass_large.dmi
  icons/obj/doors/airlocks/glass_large/overlays.dmi
  icons/obj/doors/airlocks/hatch/centcom.dmi
  icons/obj/doors/airlocks/hatch/maintenance.dmi
  icons/obj/doors/airlocks/hatch/overlays.dmi
  icons/obj/doors/airlocks/highsec/highsec.dmi
  icons/obj/doors/airlocks/highsec/overlays.dmi
  icons/obj/doors/airlocks/mask_32x32.dmi
  icons/obj/doors/airlocks/mask_64x32.dmi
  icons/obj/doors/airlocks/shuttle/overlays.dmi
  icons/obj/doors/airlocks/shuttle/shuttle.dmi
  icons/obj/doors/airlocks/station/atmos.dmi
  icons/obj/doors/airlocks/station/bananium.dmi
  icons/obj/doors/airlocks/station/command.dmi
  icons/obj/doors/airlocks/station/copper.dmi
  icons/obj/doors/airlocks/station/diamond.dmi
  icons/obj/doors/airlocks/station/engineering.dmi
  icons/obj/doors/airlocks/station/freezer.dmi
  icons/obj/doors/airlocks/station/gold.dmi
  icons/obj/doors/airlocks/station/maintenance.dmi
  icons/obj/doors/airlocks/station/maintenanceexternal.dmi
  icons/obj/doors/airlocks/station/medical.dmi
  icons/obj/doors/airlocks/station/mining.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/airlocks/station/plasma.dmi
  icons/obj/doors/airlocks/station/public.dmi
  icons/obj/doors/airlocks/station/research.dmi
  icons/obj/doors/airlocks/station/sandstone.dmi
  icons/obj/doors/airlocks/station/science.dmi
  icons/obj/doors/airlocks/station/security.dmi
  icons/obj/doors/airlocks/station/silver.dmi
  icons/obj/doors/airlocks/station/uranium.dmi
  icons/obj/doors/airlocks/station/virology.dmi
  icons/obj/doors/airlocks/station/wood.dmi
  icons/obj/doors/airlocks/station2/glass.dmi
  icons/obj/doors/airlocks/station2/overlays.dmi
  icons/obj/doors/airlocks/survival/survival.dmi
  icons/obj/doors/airlocks/survival/survival_overlays.dmi
  icons/obj/doors/airlocks/vault/overlays.dmi
  icons/obj/doors/airlocks/vault/vault.dmi
Labels: Upstream PR Merged

#350 [MIRROR] Adds a traitor spawn minor antagonist role, allows traitors to spawn on some gamemodes.
  beestation.dme
  code/game/gamemodes/clock_cult/clockcult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
  code/game/gamemodes/game_mode.dm
  code/modules/antagonists/roundstart_special/special_antagonist.dm
  code/modules/antagonists/traitor/traitor_spawner.dm
Labels: Upstream PR Merged

#352 [MIRROR] Unwhite the changeling icons
  icons/mob/actions/actions_changeling.dmi
Labels: Upstream PR Merged

#353 [MIRROR] Fixes a records runtime
  code/modules/mob/living/carbon/human/human.dm
Labels: Upstream PR Merged

#354 [MIRROR] Fixes teratomas again
  code/datums/dna.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/transform_procs.dm
Labels: Upstream PR Merged

#355 [MIRROR] Gives Blood Brothers a good way to communicate
  beestation.dme
  code/game/objects/items/implants/implant_bb.dm
  code/modules/antagonists/brother/brother.dm
Labels: Upstream PR Merged

#356 [MIRROR] fixes crate animation
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Upstream PR Merged

#348 [MIRROR] Converts decals from components to elements (but it works this time)
  _maps/map_files/BoxStation/BoxStation.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/controllers/subsystem/atoms.dm
  code/datums/components/decal.dm
  code/datums/components/forensics.dm
  code/datums/elements/_element.dm
  code/datums/elements/decal.dm
  code/datums/elements/decals/blood.dm
  code/game/atoms.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/items/defib.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
Labels: Upstream PR Merged

#357 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/README.md
Labels: Tools

#359 [MIRROR] Fix a mistake with shuttles PR
  code/game/machinery/computer/communications.dm
Labels: Upstream PR Merged

#327 [MIRROR] Removes Skewium
  code/modules/cargo/bounties/reagent.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  strings/cas_white.txt
Labels: DO NOT MERGE, Voted Out

#364 [MIRROR] Improve holiday station name picking
  code/__HELPERS/names.dm
Labels: Upstream PR Merged

#365 [MIRROR] Sanitizes layer manifolds SetInitDirections()
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
Labels: Upstream PR Merged

#366 [MIRROR] you can now VV atoms with invalid icons
  code/modules/admin/view_variables/view_variables.dm
Labels: Upstream PR Merged

#368 [MIRROR] Mechs will now knock people down on melee, rather than make them unconcious.
  code/modules/mob/living/living_defense.dm
Labels: Upstream PR Merged

#370 [MIRROR] Makes the microwave cleanable by the damp rag
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: Upstream PR Merged

#371 [MIRROR] fixes radiation filter breaking airlock filter
  code/game/machinery/doors/airlock.dm
Labels: Upstream PR Merged

#372 [MIRROR] Limbsnakes properly disember limbs
  code/modules/antagonists/changeling/powers/biodegrade.dm
  code/modules/antagonists/changeling/powers/regenerate.dm
Labels: Upstream PR Merged

#376 [MIRROR] Atmos components now nullifies node properly (Important(tm) atmos bug fix)
  code/modules/atmospherics/machinery/components/components_base.dm
Labels: Upstream PR Merged

#378 [MIRROR] Update components_base.dm
  code/modules/atmospherics/machinery/components/components_base.dm
Labels: Upstream PR Merged

#379 [MIRROR] Random Processing Reviews: Part 1
  code/_onclick/hud/alert.dm
  code/_onclick/telekinesis.dm
  code/controllers/subsystem/processing/processing.dm
  code/datums/action.dm
  code/datums/brain_damage/special.dm
  code/datums/components/chasm.dm
  code/datums/components/mood.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/radioactive.dm
  code/datums/components/rot.dm
  code/datums/elements/earhealing.dm
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/game/area/areas.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gangs/dominator.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/machinery/Beacon.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/airlock_control.dm
  code/game/machinery/airlock_cycle_control.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/cloning.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/machinery/droneDispenser.dm
  code/game/machinery/fat_sucker.dm
  code/game/objects/objs.dm
  code/modules/clothing/chameleon.dm
Labels: Upstream PR Merged

#382 [MIRROR] Fixes a examine runtime error for reinforced floor
  code/game/turfs/open/floor/reinf_floor.dm
Labels: Upstream PR Merged

#383 [MIRROR] Removes a duplicate Chair on Metastation.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Upstream PR Merged

#392 [MIRROR] Nanotrasen no longer hires minors
  code/__DEFINES/mobs.dm
Labels: Upstream PR Merged

#393 [MIRROR] Adds a new roundend sound
  sound/roundend/hot_cross_buns.ogg
Labels: Upstream PR Merged

#396 [MIRROR] Nerfs bumpslams
  code/__DEFINES/_mob_properties.dm
  code/modules/mob/living/living.dm
Labels: Upstream PR Merged

#397 [MIRROR] Unlicensed PDA starts with charcoal stylus in
  code/game/objects/items/devices/PDA/PDA_types.dm
Labels: Upstream PR Merged

#400 [MIRROR] cleans out some active turfs on the CC z level
  _maps/map_files/generic/CentCom.dmm
Labels: Upstream PR Merged

#406 [MIRROR] VV now actually shows icons
  code/modules/admin/view_variables/view_variables.dm
Labels: Upstream PR Merged

#403 [MIRROR] Fixes a var in the maps
  _maps/RandomRooms/3x5/sk_rdm063_pubbyclutter5.dmm
  _maps/RandomRooms/5x4/sk_rdm048_metatheatre.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/crashedclownship.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/research.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/hunter_russian.dmm
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship_cere.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
Labels: Upstream PR Merged

#404 [MIRROR] Lavaland map changes
  _maps/map_files/Mining/Lavaland.dmm
Labels: Upstream PR Merged

#410 [MIRROR] Captain can no longer get midround special antag lmao
  code/modules/antagonists/roundstart_special/special_antagonist.dm
Labels: Upstream PR Merged

#413 [MIRROR] Makes hostile AI ever so slightly faster
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Upstream PR Merged

#414 [MIRROR] Removes Toggling of limb specific damage
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/silicon/pai/software.dm
Labels: Upstream PR Merged

#415 [MIRROR] An attempt on fixing dynameme role protection
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Upstream PR Merged

#416 [MIRROR] Improves self-harm message formatting.
  code/_onclick/item_attack.dm
Labels: Upstream PR Merged

#418 [MIRROR] When you try to feed a beaker to someone it announces the name in chat
  code/modules/reagents/reagent_containers/glass.dm
Labels: Upstream PR Merged

#421 [MIRROR] Admins now see if the objective is currently completed in traitor panel
  code/modules/admin/antag_panel.dm
Labels: Upstream PR Merged

#422 [MIRROR] Add some simple logging to quantum spin inverter
  code/game/objects/items/devices/swapper.dm
Labels: Upstream PR Merged

#423 [MIRROR] Update regenerative.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
Labels: Upstream PR Merged

#424 [MIRROR] Station bounced radio QOL
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Upstream PR Merged

#412 [MIRROR] Gives the top contributor a coder skirt
  code/_onclick/hud/credits.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/jobs/job_types/_job.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Upstream PR Merged

#411 [MIRROR] More AT cleanup on CC and Lavaland Z Levels
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/turfs/open/floor/plating/misc_plating.dm
Labels: Upstream PR Merged

#417 [MIRROR] Fixed a deltastation firelock, this is my first time in strongdmm dont hurt me.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Upstream PR Merged

#405 [MIRROR] Fastmos mapping improvements
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/ferry_base.dmm
  _maps/shuttles/ferry_fancy.dmm
  _maps/shuttles/ferry_meat.dmm
Labels: DO NOT MERGE, Upstream PR Merged

#425 [MIRROR] ike hates fun
  code/_onclick/hud/credits.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/jobs/job_types/_job.dm
  icons/obj/clothing/uniforms.dmi
Labels: Upstream PR Merged

#428 [MIRROR] Mentor Follow go bye-bye
  code/modules/mentor/mentorhelp.dm
  code/modules/mentor/mentorpm.dm
  code/modules/mentor/mentorsay.dm
Labels: Upstream PR Merged

#420 [MIRROR] Fixes maps' pipes a bit
  OasisStation.dme
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: DO NOT MERGE, NEEDS REMIRROR, Upstream PR Merged

#430 [MIRROR] Decal fixes
  code/__DEFINES/components.dm
  code/datums/components/forensics.dm
  code/datums/elements/decal.dm
  code/datums/elements/decals/blood.dm
  code/game/objects/effects/decals/decal.dm
  code/modules/shuttle/on_move.dm
Labels: Upstream PR Merged

#431 [MIRROR] Big Medicine Rebalance V2.7
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
Labels: Upstream PR Merged

#433 [MIRROR] [s]Fix inverted check where if permanent rank changes were disabled i…
  code/modules/admin/permissionedit.dm
Labels: Upstream PR Merged

#434 [MIRROR] Cookie's Homemade Rum to maint loot table
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
Labels: Upstream PR Merged

#435 [MIRROR] Fix a hallucination runtime
  code/game/mecha/mech_fabricator.dm
  code/modules/flufftext/Hallucination.dm
Labels: Upstream PR Merged

#436 [MIRROR] Xenomorph Abilities State Plasma Cost In The Description
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/praetorian.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
Labels: Upstream PR Merged

#437 [MIRROR] [PORT] Ports tgstation/tgstation#51453 real quick
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/pump.dm
Labels: Upstream PR Merged

#438 [MIRROR] Decreases non-traitor mime forcewall duration. Traitor mime forcewall is still very good.
  code/modules/spells/spell_types/mime.dm
Labels: Upstream PR Merged

#439 [MIRROR] Fixes male underwear and shirt poking through clothes
  code/modules/mob/living/carbon/human/species.dm
Labels: Upstream PR Merged

#440 [MIRROR] [Port] Ports the long-ranged atmos analyzer
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/modules/research/designs/tool_designs.dm
Labels: Upstream PR Merged

#442 [MIRROR] Adds separate aux base access
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/access.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/mining/aux_base.dm
Labels: Upstream PR Merged

#443 [MIRROR] Webhook Processor Ports
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Upstream PR Merged

#444 [MIRROR] Adds ANZAC day
  code/modules/holiday/holidays.dm
Labels: Upstream PR Merged

#445 [MIRROR] Removes circuit atmospherics
  beestation.dme
Labels: Upstream PR Merged

#446 [MIRROR] Adds verbose logging to the emergency shuttle console
  code/modules/shuttle/emergency.dm
Labels: Upstream PR Merged

#447 [MIRROR] Fixes players getting popcap redirected if they have a mob
  code/modules/client/client_procs.dm
Labels: Upstream PR Merged

#449 [MIRROR] [PORT] logging for binary chat
  code/modules/mob/living/silicon/say.dm
Labels: Upstream PR Merged

#450 [MIRROR] [PORT] Limit how often you can use the emergency shuttle console
  code/modules/shuttle/emergency.dm
Labels: Upstream PR Merged

#451 [MIRROR] Fixes the maint rooms stormcaster told me about
  _maps/RandomRooms/10x10/sk_rdm141_6sectorsdown.dmm
  _maps/RandomRooms/10x10/sk_rdm142_olddiner.dmm
  _maps/RandomRooms/10x10/sk_rdm143_gamercave.dmm
  _maps/RandomRooms/10x10/sk_rdm144_smallmagician.dmm
  _maps/RandomRooms/10x10/sk_rdm145_ladytesla_altar.dmm
  _maps/RandomRooms/10x10/sk_rdm146_blastdoor_interchange.dmm
  _maps/RandomRooms/10x10/sk_rdm146_botany_apiary.dmm
  _maps/RandomRooms/10x10/sk_rdm147_advbotany.dmm
  _maps/RandomRooms/10x5/sk_rdm149_cratewindow.dmm
  _maps/RandomRooms/10x5/sk_rdm150_smallmedlobby.dmm
  _maps/RandomRooms/10x5/sk_rdm151_ratburger.dmm
  _maps/RandomRooms/10x5/sk_rdm152_geneticsoffice.dmm
  _maps/RandomRooms/10x5/sk_rdm153_hobowithpeter.dmm
  _maps/RandomRooms/10x5/sk_rdm154_butchersden.dmm
  _maps/RandomRooms/10x5/sk_rdm155_punjiconveyor.dmm
  _maps/RandomRooms/10x5/sk_rdm156_oldairlock_interchange.dmm
  _maps/RandomRooms/5x4/sk_rdm121_honkaccident.dmm
Labels: Upstream PR Merged
