Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2020-11, with the labels that each got.

#220 SCP-173 Maint Room and Ghost Role
  Oasis/SCP_MAIN/datums/SCP-173.dm
  Oasis/SCP_MAIN/sound/scp/spook/173Run1.mp3
  Oasis/SCP_MAIN/sound/scp/spook/173Run2.mp3
  Oasis/SCP_MAIN/sound/scp/spook/173Run3.mp3
  Oasis/_maps/RandomRooms/10x10/sk_rdm173_SCP173.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/is_helpers.dm
  code/datums/components/footstep.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/mapping/random_rooms.dm
  config/title_screens/images/singuloose.dmi
  icons/effects/effects.dmi
Labels: DO NOT MERGE, Needs Testmerge

#282 [MIRROR] Makes changelog compiles fully skips CI
  .github/workflows/test.yml
Labels: Needs Review, THIS IS VERY IMPORTANT

#331 [MIRROR] Adds a craftable charcoal pen
  code/__DEFINES/misc.dm
  code/modules/paperwork/pen.dm
  icons/obj/bureaucracy.dmi
Labels: Upstream PR Merged

#332 [MIRROR] [PORT] Blob Minor Buffs
  code/datums/saymode.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
Labels: Upstream PR Merged

#334 [MIRROR] Adds coordinate logging to admin spawn commands
  code/modules/admin/topic.dm
Labels: Upstream PR Merged

#335 [MIRROR] Actually logs shuttle name
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
Labels: Upstream PR Merged
