Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2020-10, with the labels that each got.

#51 Random AI lawset roundstart
  code/datums/ai_laws.dm
  config/game_options.txt
Labels: Test/config, enhancement

#80 Some icons added
  Oasis/icons/mob/amalgo.dmi
  Oasis/icons/mob/delirius.dmi
  Oasis/icons/obj/Factorycargo/TODO.txt
  Oasis/icons/obj/Factorycargo/furniture/machinery.dmi
  Oasis/icons/obj/Nouveau document texte.dmi
Labels: Sprites

#107 Cicuit Lab re-add (Overdrive)
  code/game/area/Space_Station_13_areas.dm
Labels: Map Edit, Revert

#103 [MIRROR] DRAGnet teleport no longer has random variance
  code/modules/projectiles/projectile/energy/net_snare.dm
Labels: Balance/Rebalance, DO NOT MERGE

#109 Circuit lab - Science Update
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit, Revert

#125 [MIRROR] Fixed Service Borg Dispensing Plasma Cigs
  code/game/objects/items/RSF.dm
Labels: Balance/Rebalance, Fix

#117 Corrects the DME again
  OasisStation.dme
Labels: Fix, Needs Review, Test/config, Upstream PR Merged
