Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2021-02, with the labels that each got.

#648 [MIRROR] Small TGUI stat panel fixes
  code/controllers/subsystem/stat.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mob/mob_stat.dm
Labels: Administration

#652 [MIRROR] Lets slow this dance down
  config/game_options.txt
Labels: Config Update

#654 [MIRROR] Allow Admins to Add/Remove Traits (tg#45503)
  beestation.dme
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/datumvars.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration

#658 [MIRROR] [bounty] transformative Crossbreeds (black)
  beestation.dme
  code/__DEFINES/mobs.dm
  code/_onclick/other_mobs.dm
  code/datums/mind.dm
  code/datums/spawners_menu.dm
  code/game/atoms_movable.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/obj_defense.dm
  code/modules/cargo/exports/xenobio.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/transformative.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/core_removal.dm
  icons/obj/slimecrossing.dmi
Labels: Sprites

#656 [MIRROR] Oozeling Sprite Changes
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Sprites

#659 [MIRROR] Better Spells Vol. 2
  code/datums/action.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/cluwnecurse.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Administration

#670 [MIRROR] Replaces plasmaglass windows on lavaland with a lava moat.
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping

#664 [MIRROR] Pool party
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/shuttles/emergency_luxury.dmm
  beestation.dme
  code/__DEFINES/components.dm
  code/__DEFINES/movespeed_modification.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/squidpeople.dm
  code/modules/pool/components/swimming.dm
  code/modules/pool/components/swimming_dissolve.dm
  code/modules/pool/components/swimming_ethereal.dm
  code/modules/pool/components/swimming_felinid.dm
  code/modules/pool/components/swimming_golem.dm
  code/modules/pool/components/swimming_squid.dm
  code/modules/pool/pool.dm
  code/modules/pool/pool_items.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/pool.dmi
  sound/effects/splash.ogg
  sound/effects/splosh.ogg
Labels: Sound, Sprites, mapping

#677 emergency fix (#3535)
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/modules/pool/components/swimming.dm
Labels: mapping

#704 Energy reduction and movement speed tweak
  code/modules/projectiles/ammunition/energy/stun.dm
  config/game_options.txt
Labels: Config Update

#638 Adds Qwerty Plushie
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#705 Randomized engines
  _maps/RandomRooms/Box/sk_ren003Box.dmm
  _maps/RandomRooms/Box/sk_ren004Box.dmm
  _maps/RandomRooms/Meta/sk_ren001Meta.dmm
  _maps/RandomRooms/Meta/sk_ren002Meta.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
Labels: mapping

#708 Fixed meta's engine alarm being in the wrong area.
  _maps/RandomRooms/Meta/sk_ren002Meta.dmm
Labels: mapping

#650 [MIRROR] Insecure Crosscomms newscasters and small QoL
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/comms.dm
  code/controllers/subsystem/ticker.dm
  code/datums/world_topic.dm
  code/game/machinery/computer/communications.dm
  config/Sage/comms.txt
  config/comms.txt
Labels: Config Update

#681 [MIRROR] Adds an atmosbot to the mining base and fixes up outpost access
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping

#711 Movement speed work
  config/game_options.txt
Labels: Config Update

#707 Adds a cool looking sweatband
  Oasis/code/modules/clothing/head/sweatband.dm
  OasisStation.dme
  _maps/map_files/EndoStation/EndoStation.dmm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  icons/mob/head.dmi
  icons/mob/sweatband.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, mapping

#722 Fixes engine mix not connecting properly.
  _maps/RandomRooms/Box/sk_ren003Box.dmm
  _maps/RandomRooms/Box/sk_ren004Box.dmm
  _maps/RandomRooms/Meta/sk_ren001Meta.dmm
  _maps/RandomRooms/Meta/sk_ren002Meta.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#728 Fixes the SM meta engine in the wrong area again.
  _maps/RandomRooms/Meta/sk_ren002Meta.dmm
Labels: mapping

#714 [port] RBMK reactor from nsv13 plus austation port and reworks.
  Oasis/code/_HELPERS/matrices.dm
  Oasis/code/modules/mining/equipment/survival_pod.dm
  Oasis/code/modules/mining/shelters.dm
  Oasis/code/modules/power/reactor/fuel_rods.dm
  Oasis/code/modules/power/reactor/rbmk.dm
  Oasis/code/modules/power/reactor/reactor_cargo.dm
  Oasis/icons/obj/computer.dmi
  Oasis/icons/obj/control_rod.dmi
  Oasis/icons/obj/inflatable.dmi
  Oasis/icons/obj/machinery/rbmk.dmi
  Oasis/icons/obj/machinery/reactor_parts.dmi
  Oasis/sound/effects/rbmk/alarm.ogg
  Oasis/sound/effects/rbmk/meltdown.ogg
  Oasis/sound/effects/rbmk/reactor_hum.ogg
  Oasis/sound/effects/rbmk/switch.ogg
  Oasis/sound/effects/rbmk/switch2.ogg
  Oasis/sound/effects/rbmk/switch3.ogg
  Oasis/sound/effects/rbmk/turbine_end.ogg
  Oasis/sound/effects/rbmk/turbine_mid.ogg
  Oasis/sound/effects/rbmk/turbine_start.ogg
  Oasis/sound/effects/ship/freespace2/crane_1.wav
  Oasis/sound/effects/ship/reactor/falloutwind.ogg
  Oasis/sound/effects/ship/reactor/startup.ogg
  Oasis/sound/effects/ship/reactor/startup2.ogg
  OasisStation.dme
  _maps/templates/reactor_1.dmm
  code/__DEFINES/sound.dm
  code/__HELPERS/maths.dm
  code/__HELPERS/matrices.dm
  code/modules/cargo/exports/engineering.dm
  code/modules/cargo/packs.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/tgs/includes.dm
  code/modules/uplink/uplink_items.dm
  tgui/packages/tgui/interfaces/NtosRbmkStats.js
  tgui/packages/tgui/interfaces/RbmkControlRods.js
  tgui/packages/tgui/interfaces/RbmkStats.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: TGUI-Changes, mapping

#733 [port] Ports 19x15 from TG
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/hud.dm
  code/_onclick/hud/human.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/crafting/crafting.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  config/Sage/config.txt
  config/config.txt
Labels: Config Update, mapping

#738 Adds the rbmk reactor to meta station, and fixes engine injectors being in the wrong area.
  OasisStation.dme
  _maps/RandomRooms/Box/sk_ren003Box.dmm
  _maps/RandomRooms/Box/sk_ren004Box.dmm
  _maps/RandomRooms/Box/sk_ren005Box.dmm
  _maps/RandomRooms/Meta/sk_ren001Meta.dmm
  _maps/RandomRooms/Meta/sk_ren002Meta.dmm
  _maps/RandomRooms/Meta/sk_ren003Meta.dmm
  code/modules/mapping/random_rooms.dm
Labels: mapping

#750 AI multicams fixed
  code/modules/mob/living/silicon/ai/multicam.dm
Labels: Fix, bug

#647 [MIRROR] New Away Mission map
  Oasis/code/modules/mob/living/simple_animal/hostile/desert_mobs.dm
  _maps/RandomZLevels/TheFactory.dmm
  beestation.dme
  code/modules/awaymissions/mission_code/TheFactory.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  config/awaymissionconfig.txt
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
  sound/ambience/ambibasement.ogg
  sound/ambience/ambiearth.ogg
  sound/ambience/ambiearthduring.ogg
  sound/ambience/ambifac.ogg
  sound/ambience/ambiwind.ogg
  sound/ambience/secrets.ogg
  sound/ambience/singulambience.ogg
  sound/creatures/bosspain.ogg
  sound/creatures/bosspain2.ogg
  sound/creatures/bosssight.ogg
  sound/creatures/bosssight2.ogg
  sound/creatures/guarddeath.ogg
  sound/creatures/guarddeath2.ogg
  sound/creatures/guarddeath3.ogg
  sound/creatures/guarddeath4.ogg
  sound/creatures/heavydeath1.ogg
  sound/creatures/heavysight1.ogg
  sound/creatures/psycdeath1.ogg
  sound/creatures/psycdeath2.ogg
  sound/creatures/psychattack1.ogg
  sound/creatures/psychdeath.ogg
  sound/creatures/psychdeath2.ogg
  sound/creatures/psychhead.ogg
  sound/creatures/psychhead2.ogg
  sound/creatures/psychidle.ogg
  sound/creatures/psychidle2.ogg
  sound/creatures/psychsight.ogg
  sound/creatures/psychsight2.ogg
  sound/creatures/psycidle1.ogg
  sound/creatures/psycidle2.ogg
  sound/creatures/psycidle3.ogg
  sound/creatures/szombiedeath.ogg
  sound/creatures/szombiesight.ogg
  sound/creatures/szombiesight2.ogg
  sound/creatures/wardendeath.ogg
  sound/effects/radio3.ogg
  sound/spookoween/spookywind.ogg
  sound/weapons/attributions.txt
  sound/weapons/deaglelock.ogg
  sound/weapons/deaglerack.ogg
  sound/weapons/deagleshot.ogg
  sound/weapons/deagleslidedrop.ogg
  sound/weapons/heavyminigunshoot.ogg
  sound/weapons/heavyminigunstart.ogg
  sound/weapons/heavyminigunstop.ogg
  sound/weapons/leveractionrack.ogg
  sound/weapons/leveractionshot.ogg
Labels: Config Update, DO NOT MERGE, Sound, Sprites, mapping

#660 [MIRROR] 0 gax mixes and unstated temperatures purged
  _maps/RandomZLevels/TheFactory.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/modules/awaymissions/mission_code/snowdin.dm
Labels: mapping

#676 [MIRROR] Cap slaughter & laughter demons to 1 each
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Needs Vote

#690 [MIRROR] Elite Strike Team Location Track Assister 9000
  beestation.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/datums/action.dm
  code/datums/components/team_monitor.dm
  code/game/alternate_appearance.dm
  code/game/machinery/syndicatebomb.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/actions.dmi
  icons/mob/hud.dmi
Labels: Sprites

#692 [MIRROR] Add turret control panel to the syndicate shuttle
  _maps/shuttles/infiltrator_basic.dmm
  code/game/machinery/porta_turret/portable_turret.dm
Labels: mapping

#752 Adds the High Frequency Blade(from hippie)
  OasisStation.dme
  code/game/objects/items/melee/hfblade.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/hfblade.dmi
  icons/mob/inhands/weapons/melee_lefthandhf.dmi
  icons/mob/inhands/weapons/melee_righthandhf.dmi
  icons/obj/hfblade.dmi
  sound/misc/desceration-01.ogg
  sound/misc/desceration-02.ogg
Labels: Feature, Sound, Sprites

#730 Heretics Minimum pop of 20
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#764 Poll sound as asked by Overdrive
  code/modules/admin/poll_management.dm
Labels: Administration, Feature, Needs Testmerge

#757 High frequency blade vol.2 electric boogalo (from hippie)
  OasisStation.dme
  code/game/objects/items/melee/hfblade.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/hfblade.dmi
  icons/mob/inhands/weapons/melee_lefthandhf.dmi
  icons/mob/inhands/weapons/melee_righthandhf.dmi
  icons/obj/hfblade.dmi
  sound/misc/desceration-01.ogg
  sound/misc/desceration-02.ogg
  sound/weapons/hfblade-music1.ogg
  sound/weapons/hfblade-music2.ogg
Labels: Sound, Sprites

#696 [MIRROR] New antag objective: Steal Blackbox (tg#49298)
  code/game/gamemodes/objective_items.dm
  code/game/machinery/telecomms/machines/message_server.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites

#765 Adds Random Engines to Endo plus vending machine
  _maps/RandomRooms/Box/sk_ren005Box.dmm
  _maps/RandomRooms/Endo/sk_ren006Endo.dmm
  _maps/RandomRooms/Endo/sk_ren007Endo.dmm
  _maps/RandomRooms/Endo/sk_ren008Endo.dmm
  _maps/RandomRooms/Meta/sk_ren003Meta.dmm
  _maps/map_files/EndoStation/EndoStation.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
  code/modules/vending/citadelplush.dm
  icons/obj/vending.dmi
Labels: Sprites, mapping

#673 [MIRROR] Makes it harder to meta heretics through poppies and kitchen knives
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/under/accessories.dm
  icons/obj/clothing/accessories.dmi
Labels: Sprites

#783 should fix runtime issues
  _maps/RandomRooms/Box/sk_ren005Box.dmm
Labels: mapping

#782 [MIRROR] Miscellaneous fixes (2021-02-17)
  code/controllers/subsystem/ambience.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/admin/sql_message_system.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/cargo/packs.dm
  code/modules/crew_objectives/security_objectives.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Administration

#772 [MIRROR] Miscellaneous Fixes (2021-02-16)
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/objects.dm
  code/datums/components/team_monitor.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/admin/permissionedit.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/power/singularity/collector.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/research/rdconsole.dm
  code/modules/tgui/tgui.dm
Labels: Administration

#784 adds analyzer to room and few minor changes
  _maps/RandomRooms/Meta/sk_ren003Meta.dmm
Labels: mapping

#778 [MIRROR] Adds vault door to gulag
  _maps/map_files/Mining/Lavaland.dmm
Labels: mapping

#790 fixes room spawner
  OasisStation.dme
  _maps/RandomRooms/Box/sk_ren005Box.dmm
  _maps/map_files/EndoStation/EndoStation.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
  code/modules/vending/citadelplush.dm
Labels: DO NOT MERGE, Sprites, mapping

#795 [MIRROR] Emoji filtered word fix
  icons/emoji.dmi
Labels: Sprites

#776 [MIRROR] Adds gas miners to every map. There are 3 maps that already have them, all maps should have them.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#796 Randomendofix
  _maps/RandomRooms/Box/sk_ren004Box.dmm
  _maps/RandomRooms/Box/sk_ren005Box.dmm
  _maps/RandomRooms/Endo/sk_ren006Endo.dmm
  _maps/RandomRooms/Meta/sk_ren001Meta.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/EndoStation/EndoStation.dmm
Labels: mapping

#734 [MIRROR] Oozeling translucency tweak
  icons/mob/human_parts_greyscale.dmi
Labels: Sprites

#753 [MIRROR] Added the ability to freely change chat fonts
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/middleware.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui/styles/components/Dropdown.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#799 Attempt at runtime fix
  _maps/RandomRooms/Box/sk_ren005Box.dmm
Labels: mapping

#800 [MIRROR] Some balance changes on Factory away mission
  _maps/RandomZLevels/TheFactory.dmm
  code/modules/awaymissions/mission_code/TheFactory.dm
Labels: mapping

#801 [MIRROR] Solves centcom escape exploits.
  _maps/map_files/generic/CentCom.dmm
  code/game/turfs/closed/wall/misc_walls.dm
  icons/turf/walls.dmi
Labels: Sprites, mapping

#672 [MIRROR] tgui: Abductors
  beestation.dme
  code/modules/antagonists/abductor/equipment/orderable_gear.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/antagonists/abductor/machinery/dispenser.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  tgui/packages/tgui/interfaces/AbductorConsole.js
  tgui/packages/tgui/interfaces/GlandDispenser.js
  tgui/packages/tgui/interfaces/ProbingConsole.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#803 Removes random space engine and fixes some stuff
  _maps/RandomRooms/Box/sk_ren005Box.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/turfs/open/_open.dm
Labels: mapping

#723 [MIRROR] Small crate animation adjustments and coffin animation
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/crates/critter.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  icons/obj/crates.dmi
Labels: Sprites

#716 [MIRROR] [PORT] 2 PRs from Project>Features, missed file change
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/components/material_container.dm
  code/game/machinery/computer/arcade.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: mapping

#792 [MIRROR] Re-adds apid dash, adds honeycomb crafting for apids
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/datums/action.dm
  code/datums/components/crafting/crafting.dm
  code/datums/mutations/cold.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/tiles/tile_mineral.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species_types/apid.dm
  code/modules/mob/living/living.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/inhands/misc/tiles_lefthand.dmi
  icons/mob/inhands/misc/tiles_righthand.dmi
  icons/obj/tiles.dmi
Labels: Sprites

#797 [MIRROR] Fix pubby SM roundstart gas mix
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#729 Adds tiny fans to all mining shuttles
  _maps/shuttles/mining_box.dmm
  _maps/shuttles/mining_delta.dmm
  _maps/shuttles/mining_kilo.dmm
  _maps/shuttles/mining_large.dmm
Labels: mapping

#691 [MIRROR] Removes ancient synth
  _maps/RandomZLevels/TheFactory.dmm
  code/modules/awaymissions/mission_code/TheFactory.dm
Labels: mapping

#816 Updated bishop outfit sprites, added bishop cloak and black bishop ou…
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/chaplainsuits.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/neck.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#657 [MIRROR] Bluespace Miner Config
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/research/techweb/all_nodes.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Balance/Rebalance, Config Update, Voted Out

#793 [MIRROR] Cap slimepeople duping
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#817 [MIRROR] adds air alarm to morgue on Box Station
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#823 Some fixes
  Oasis/code/datums/ai_laws.dm
  icons/obj/device.dmi
Labels: Sprites

#820 [MIRROR] Updates Herald sprites, animations and prophet cloak.
  icons/mob/lavaland/lavaland_elites.dmi
  icons/mob/neck.dmi
  icons/obj/lavaland/elite_trophies.dmi
Labels: Sprites

#824 [MIRROR] Crucifixes and Warding Off Curses
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/cargo/packs.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/curse.dm
  code/modules/vending/wardrobes.dm
  icons/obj/objects.dmi
Labels: Sprites

#832 [MIRROR] make ruko happy / add a cautery to CentCom
  _maps/map_files/generic/CentCom.dmm
Labels: mapping

#829 Medicine nerf rebalance
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, DO NOT MERGE, Needs Rebalancing

#833 [PORT] Resprites from white sands that makes weapons look sexier.
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Sprites

#835 [MIRROR] Remove the extended gamemode from Sage
  config/Sage/game_options.txt
  config/game_options.txt
Labels: Config Update

#836 [MIRROR] Disable jobs.txt loading.
  config/Sage/config.txt
  config/config.txt
Labels: Config Update

#840 [MIRROR] Miscellaneous fixes (2021-02-19)
  code/modules/admin/antag_panel.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Administration

#847 [MIRROR] [bounty] Warping Crossbreeds (bluespace)
  _maps/templates/warped_room.dmm
  beestation.dme
  code/game/objects/effects/forcefields.dm
  code/game/objects/empulse.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/crossbreeding/warping.dm
  code/modules/research/xenobiology/xenobiology.dm
  icons/obj/slimecrossing.dmi
Labels: Sprites, mapping

#854 [MIRROR] add a real microwave to the bluesbace room.
  _maps/templates/warped_room.dmm
Labels: mapping

#864 station v station held together with shitcode and flextape
  Oasis/code/_HELPERS/matrices.dm
  Oasis/code/modules/stationversusstation/jobspawns.dm
  Oasis/code/modules/stationversusstation/machines.dm
  Oasis/code/modules/stationversusstation/map_areas/blue_areas.dm
  Oasis/code/modules/stationversusstation/map_areas/red_areas.dm
  Oasis/code/modules/stationversusstation/svs_job.dm
  Oasis/code/modules/stationversusstation/tcomms_presets.dm
  OasisStation.dme
  _maps/facingworlds.json
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/maps.dm
  code/controllers/subsystem/job.dm
  code/datums/map_config.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/maps.txt
Labels: Config Update, mapping

#865 FW Fixes
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
Labels: mapping

#867 Fixes alot of missing shit.
  Oasis/code/modules/stationversusstation/map_areas/blue_areas.dm
  _maps/RandomRooms/Middle/no_mans_land1.dmm
  _maps/RandomRooms/Middle/no_mans_land2.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/labour_box.dmm
  code/game/objects/effects/spawners/roomspawner.dm
  code/modules/mapping/random_rooms.dm
Labels: mapping

#843 [MIRROR] Metastation Coldroom and Cryogenics fixes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#870 decals update+ news ones
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_maps.dm
  icons/obj/decals.dmi
Labels: Sprites

#872 New suit_storage (red and blue)
  code/game/machinery/suit_storage_unit.dm
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/machines/suit_storage.dmi
Labels: Sprites

#871 Fixes lavaland for now.
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
  _maps/map_files/Mining/Lavaland-SvS.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/labour_box.dmm
Labels: mapping

#874 SvS Changes
  _maps/RandomRooms/Middle/no_mans_land2.dmm
  _maps/RandomRuins/SpaceRuins/scav_mining.dmm
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
Labels: mapping

#877 map improvment + more team sprites
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
  code/game/objects/structures/beds_chairs/chair.dm
  icons/mob/inhands/misc/chairs_lefthand.dmi
  icons/mob/inhands/misc/chairs_righthand.dmi
  icons/obj/chairs.dmi
Labels: Merge Conflict, Sprites, mapping

#881 Update of Overdrive and mine merge together
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
Labels: mapping
