Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2021-01, with the labels that each got.

#453 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/api.dm
Labels: Tools

#515 [MIRROR] Space Ambience Music: 'Starlight'
  code/__DEFINES/sound.dm
  sound/ambience/qwerty/starlight.ogg
Labels: Sound

#593 [MIRROR] Border firelock frames can now be walked through
  code/game/machinery/doors/firedoor.dm
  icons/obj/doors/edge_Doorfire.dmi
Labels: Sprites

#597 [MIRROR] Replaces remnants of old firelocks on most maps
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#602 [MIRROR] space ruins but they don't destroy themselves by a random spessman that just opened a door
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
Labels: mapping

#605 [MIRROR] Coffee Cart
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
Labels: mapping

#611 [MIRROR] Roundstart Slimepeople Race: Oozelings
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/packs.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/surgery/organs/lungs.dm
  config/Sage/game_options.txt
  config/game_options.txt
  strings/names/ooze_first.txt
  strings/names/ooze_last.txt
Labels: config

#617 [MIRROR] Adjusts the file labels slightly and makes it a bit easier to read
  .github/file_labeler.yml
Labels: GitHub

#622 [MIRROR] Mastermode is stored as a configuration entry
  code/_globalvars/game_modes.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/topic.dm
  config/Sage/game_options.txt
  config/game_options.txt
Labels: config

#624 [MIRROR] Clearer secHUD icons
  icons/mob/hud.dmi
Labels: Sprites

#628 [MIRROR] [PORT?] Reworks lighting overlay
  code/modules/power/lighting.dm
  icons/obj/lighting_overlay.dmi
Labels: Sprites

#633 [MIRROR] [PORT] SuperLube! from TG
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/datums/components/wet_floor.dm
  code/game/turfs/open/_open.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: mapping

#634 [MIRROR] Fixes another MacSpace stuff
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  code/game/turfs/open/water.dm
Labels: mapping

#639 [MIRROR] Update axios to 0.21.1
  tgui/packages/tgui-dev-server/package.json
  tgui/yarn.lock
Labels: TGUI-Changes
