Repository Oasis-SS13/Oasis-SS13, pull requests merged in 2021-03, with the labels that each got.

#885 FacingWorld Update of security on both side.
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
Labels: mapping

#899 Removes Facingworlds from voting, and increases min pop.
  config/maps.txt
Labels: Config Update

#913 Burger vending machine added
  OasisStation.dme
  _maps/map_files/FacingWorlds/FacingWorlds.dmm
  code/modules/vending/burger.dm
  icons/obj/vending.dmi
Labels: Sprites, mapping

#905 [MIRROR] adds file cabinet to HoP's office on meta
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#912 Small antag rework.
  config/game_options.txt
Labels: Config Update, Voted In

#883 [PORT] Yogstations teg visual update.
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/power/generator.dm
  icons/obj/machines/thermoelectric.dmi
Labels: Sprites

#923 [MIRROR] Miscellaneous fixes (2021-02-24)
  _maps/RandomZLevels/TheFactory.dmm
  code/datums/dna.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/effects/mainttraps.dm
  code/game/objects/items/RCD.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/guardian/abilities/special/absolution.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/surgery/blood_filter.dm
  code/modules/vehicles/wheelchair.dm
Labels: mapping

#869 [MIRROR] Fixes Brig Physician permissions / Sec perm cleanup
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/access.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/warden.dm
Labels: mapping

#951 [MIRROR] Adds a handful of nice sprite related things from TG. (Inhands etc.)
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/misc/bedsheet_lefthand.dmi
  icons/mob/inhands/misc/bedsheet_righthand.dmi
  icons/mob/inhands/misc/sheets_lefthand.dmi
  icons/mob/inhands/misc/sheets_righthand.dmi
  icons/mob/inhands/weapons/flamethrower_lefthand.dmi
  icons/mob/inhands/weapons/flamethrower_righthand.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
Labels: Sprites

#952 Fixes my facing worlds fuck up
  config/maps.txt
Labels: Config Update

#948 [MIRROR] Removes freezer from metastation kitchen backroom
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#953 syndi_tele sprite fix
  icons/obj/device.dmi
Labels: Sprites

#946 [MIRROR] removes unused/bad helpers
  code/__HELPERS/_lists.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/ticker.dm
  code/datums/helper_datums/events.dm
  code/game/machinery/newscaster.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha.dm
  code/modules/admin/admin.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Administration

#937 [MIRROR] Stops the box mining dock from plasmaflooding itself.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#878 [MIRROR] Hygiene is now tied to mood
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/mobs.dm
  code/datums/components/mood.dm
  code/datums/mood_events/needs_events.dm
  code/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Balance/Rebalance, Needs Vote

#936 [MIRROR] Extremely minor box station adjustments
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#955 Coalition map sign
  code/game/objects/structures/signs/signs_maps.dm
  icons/obj/decals.dmi
Labels: Sprites

#959 Revertion of radnerf.
  code/__DEFINES/maths.dm
  code/__DEFINES/radiation.dm
  code/__HELPERS/radiation.dm
  code/datums/components/rad_insulation.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
Labels: Needs Review, Needs Testmerge, Revert

#972 Port's blood splatter from hippie
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Port

#956 Adds el shoepacabra ghost spawner
  Oasis/code/_onclick/hud/shoepacabra.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/death.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/door_breaker.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/emotes.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/forms/greater.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/forms/lesser.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/life.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/organs.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/powers.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/shoepacabra.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/shoepacabra_defense.dm
  Oasis/code/modules/mob/living/carbon/shoepacabra/update_icons.dm
  Oasis/code/modules/projectiles/projectile/special/shoepacabra_spit.dm
  Oasis/icons/mob/shoepacabra/actions.dmi
  Oasis/icons/mob/shoepacabra/shoepacabra.dmi
  Oasis/icons/mob/shoepacabra/shoepacabra_leaping.dmi
  Oasis/icons/obj/mob_spawner.dmi
  Oasis/icons/obj/projectiles.dmi
  OasisStation.dme
  _maps/RandomRooms/3x3/sk_rdm157_abandoned_taco_stand.dmm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/shoepacabras.dm
  code/_onclick/other_mobs.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/language/language_holder.dm
  code/modules/language/shoepacabrish.dm
  code/modules/lighting.dm
  code/modules/mapping/random_rooms.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
Labels: mapping

#976 Ports nanosuit from hippie
  beestation.dme
  code/modules/clothing/spacesuits/nanosuit.dm
  icons/mob/actions/actions_nanosuit.dmi
  icons/mob/nanosuit.dmi
  icons/obj/nanosuit.dmi
Labels: Port, Sprites

#978 Reverts nanosuit add,
  beestation.dme
  code/modules/clothing/spacesuits/nanosuit.dm
  icons/mob/actions/actions_nanosuit.dmi
  icons/mob/nanosuit.dmi
  icons/obj/nanosuit.dmi
Labels: Sprites

#979 Adds a new pistol.
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites

#958 adds Cuban Pete and plushie to box and meta
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#981 Greed Die + some miscellaneous
  code/game/objects/items/dice.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/spells/spell_types/santa.dm
  icons/mob/actions/actions_spells.dmi
  icons/obj/dice.dmi
  icons/obj/economy.dmi
Labels: Sprites

#984 fixes Box Maint
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: mapping

#980 [MIRROR] Clockwork cult gear base fixes
  code/modules/antagonists/clock_cult/scriptures/interdiction_lens.dm
  code/modules/antagonists/clock_cult/scriptures/prosperity_prism.dm
  code/modules/antagonists/clock_cult/structure/gear_base.dm
  icons/obj/clockwork_objects.dmi
Labels: Sprites

#873 [MIRROR] Upgrades TGUI's marked dependency to ^2.0.0
  tgui/packages/tgui/package.json
  tgui/public/tgui-common.chunk.js
  tgui/yarn.lock
Labels: TGUI-Changes

#994 [Port] tgui: RCD Access Control
  code/game/objects/items/RCD.dm
Labels: Port

#995 Telecommunications Updated Machine UI fixed
  code/_globalvars/misc.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/receiver.dm
  tgui/packages/tgui/interfaces/Telecomms.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#997 Revert "Telecommunications Updated Machine UI fixed"
  code/_globalvars/misc.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/receiver.dm
  tgui/packages/tgui/interfaces/Telecomms.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#926 [MIRROR] [Port] Telecommunications Updated Machine UI
  code/_globalvars/misc.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/receiver.dm
  tgui/packages/tgui/interfaces/Telecomms.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#1002 [MIRROR] Ports: Ghost Pool Protection Admin Button
  OasisStation.dme
  beestation.dme
  code/__DEFINES/admin.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/pai.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/objects/items/holy_weapons.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/ghost_pool_protection.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/corpse.dm
  code/modules/events/_event.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  tgui/packages/tgui/interfaces/GhostPoolProtection.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administration, TGUI-Changes

#1004 Adds the TGUI Fabricator.
  OasisStation.dme
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/exosuit_fab.dm
  code/controllers/subsystem/timer.dm
  code/datums/datum.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/research/designs.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/medical_designs.dm
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Port, TGUI-Changes

#987 [PORT] Shuttle station, a station but on a shuttle.
  OasisStation.dme
  _maps/_basemap.dm
  _maps/map_files/Shipstation/ShipStation.dmm
  _maps/map_files/Shipstation/job_changes.dm
  _maps/shipstation.json
  _maps/shuttles/station_ship.dmm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/modules/jobs/map_changes/map_changes.dm
  code/modules/shuttle/shipstation.dm
  config/maps.txt
Labels: Config Update, mapping

#1005 [MIRROR] Fixes a battle royale typo
  code/modules/admin/battle_royale.dm
Labels: Administration

#988 [MIRROR] War Declaration Music
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  sound/soundtrack/future_perception.ogg
Labels: Sound

#846 Automatic TGS DMAPI Update
  code/modules/tgs/includes.dm
Labels: Tools

#1013 removes shipstation from rotation atleast for now
  config/maps.txt
Labels: Config Update

#1017 [MIRROR] Standarizes coldroom tiles, removes roundstart cold tile.
  _maps/RandomRooms/5x4/sk_rdm124_oldcryoroom.dmm
  _maps/RandomZLevels/TheFactory.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/atmospherics.dm
  code/game/turfs/open/floor/plasteel_floor.dm
Labels: mapping

#1009 Clowndola
  Oasis/code/modules/hydroponics/grown/mushrooms.dm
  Oasis/code/modules/mob/living/simple_animal/hostile/mushroom.dm
  Oasis/code/modules/mob/living/simple_animal/hostile/retaliate/clowndola.dm
  Oasis/code/modules/mob/living/simple_animal/hostile/retaliate/desert_mobs.dm
  Oasis/code/modules/mob/living/simple_animal/hostile/retaliate/mushroom.dm
  OasisStation.dme
  beestation.dme
  code/datums/diseases/transformation.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/friendly/gondola.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/mob/gondola.dmi
  icons/mob/gondolas.dmi
  icons/obj/food/food.dmi
Labels: DO NOT MERGE, Feature, Feature Request, Sprites

#1019 Fix shitstation
  _maps/RandomRooms/Meta/sk_ren003Meta.dmm
  _maps/map_files/Shipstation/ShipStation.dmm
  _maps/shipstation.json
  _maps/shuttles/station_ship.dmm
Labels: mapping

#1035 [MIRROR] Quick-Create-Antagonist tweaks
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
Labels: Administration

#1067 blackmarket
  Oasis/code/controllers/subsystem/blackmarket.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_item.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/consumables.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/tools.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_market.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_telepad.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_uplink.dm
  OasisStation.dme
  code/__DEFINES/blackmarket.dm
  code/game/machinery/_machinery.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/blackmarket.dmi
  tgui/packages/tgui/interfaces/BlackmarketUplink.js
  tgui/packages/tgui/routes.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/webpack.config.js
Labels: Sprites, TGUI-Changes

#1068 Revert "blackmarket"
  Oasis/code/controllers/subsystem/blackmarket.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_item.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/consumables.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/tools.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_market.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_telepad.dm
  Oasis/code/modules/cargo/blackmarket/blackmarket_uplink.dm
  OasisStation.dme
  code/__DEFINES/blackmarket.dm
  code/game/machinery/_machinery.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/blackmarket.dmi
  tgui/packages/tgui/interfaces/BlackmarketUplink.js
  tgui/packages/tgui/routes.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/webpack.config.js
Labels: Sprites, TGUI-Changes

#1069 Blackmarket
  Oasis/code/controllers/subsystem/blackmarket.dm
  OasisStation.dme
  code/__DEFINES/blackmarket.dm
  code/controllers/subsystem/blackmarket.dm
  code/game/machinery/_machinery.dm
  code/modules/cargo/blackmarket/blackmarket_item.dm
  code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
  code/modules/cargo/blackmarket/blackmarket_items/consumables.dm
  code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  code/modules/cargo/blackmarket/blackmarket_items/tools.dm
  code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
  code/modules/cargo/blackmarket/blackmarket_market.dm
  code/modules/cargo/blackmarket/blackmarket_telepad.dm
  code/modules/cargo/blackmarket/blackmarket_uplink.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/blackmarket.dmi
  tgui/packages/tgui/interfaces/BlackmarketUplink.js
  tgui/packages/tgui/routes.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/webpack.config.js
Labels: Sprites, TGUI-Changes

#1073 Moretgui for blackmarket uplink
  code/__DEFINES/blackmarket.dm
  code/modules/cargo/blackmarket/blackmarket_item.dm
  code/modules/cargo/blackmarket/blackmarket_market.dm
  tgui/packages/tgui/interfaces/BlackmarketUplink.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#1039 [MIRROR] TG PORT: New sprite animation
  icons/mob/mutant_bodyparts.dmi
Labels: Sprites
